# Generated by Django 5.0.3 on 2024-09-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemarot',
            name='perek',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='massekhet',
            name='perek',
            field=models.IntegerField(default=1),
        ),
    ]
