# Generated by Django 5.0.3 on 2024-03-10 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gemarot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gemara',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gemara',
            name='name',
        ),
        migrations.AlterField(
            model_name='gemara',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainApp.session'),
        ),
        migrations.AddField(
            model_name='gemara',
            name='gemarot_ptr',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ChainApp.gemarot'),
        ),
    ]
