# Generated by Django 5.0.3 on 2024-09-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainApp', '0002_gemarot_perek_massekhet_perek'),
    ]

    operations = [
        migrations.AddField(
            model_name='gemara',
            name='choose_perek',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='michna',
            name='choose_perek',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
