# Generated by Django 5.0.3 on 2024-10-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainApp', '0002_annonces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonces',
            name='date',
        ),
        migrations.AlterField(
            model_name='annonces',
            name='lien',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
