# Generated by Django 5.0.3 on 2024-09-10 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gemarot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('livre', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Gemarot',
                'verbose_name_plural': 'Gemarot',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
            },
        ),
        migrations.CreateModel(
            name='Seder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Seder',
                'verbose_name_plural': 'Sederim',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Massekhet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('seder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='massekhtot', to='ChainApp.seder')),
            ],
            options={
                'verbose_name': 'Massekhet',
                'verbose_name_plural': 'Massekhtot',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_limit', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('session_is', models.BooleanField(choices=[(True, 'Mishna'), (False, 'Gemara')], default=False)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChainApp.person')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Michna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('choose_michna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainApp.massekhet')),
                ('chosen_by_guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChainApp.guest')),
                ('chosen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChainApp.person')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainApp.session')),
            ],
            options={
                'verbose_name': 'Michna',
                'verbose_name_plural': 'Michna',
            },
        ),
        migrations.CreateModel(
            name='Gemara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('choose_gemarot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainApp.gemarot')),
                ('chosen_by_guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChainApp.guest')),
                ('chosen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChainApp.person')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainApp.session')),
            ],
            options={
                'verbose_name': 'Gemara',
                'verbose_name_plural': 'Gemara',
            },
        ),
    ]
