# Generated by Django 5.0.3 on 2024-09-22 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainApp', '0004_gemara_is_completed_michna_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('link', models.URLField(blank=True)),
                ('total_sections', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Text Study',
                'verbose_name_plural': 'Text Studies',
            },
        ),
        migrations.RemoveField(
            model_name='gemara',
            name='choose_gemarot',
        ),
        migrations.RemoveField(
            model_name='gemara',
            name='chosen_by',
        ),
        migrations.RemoveField(
            model_name='gemara',
            name='chosen_by_guest',
        ),
        migrations.RemoveField(
            model_name='gemara',
            name='session',
        ),
        migrations.RemoveField(
            model_name='massekhet',
            name='seder',
        ),
        migrations.RemoveField(
            model_name='michna',
            name='choose_michna',
        ),
        migrations.RemoveField(
            model_name='michna',
            name='chosen_by',
        ),
        migrations.RemoveField(
            model_name='michna',
            name='chosen_by_guest',
        ),
        migrations.RemoveField(
            model_name='michna',
            name='session',
        ),
        migrations.RemoveField(
            model_name='session',
            name='session_is',
        ),
        migrations.CreateModel(
            name='TextStudyReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('section', models.IntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('chosen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChainApp.person')),
                ('chosen_by_guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ChainApp.guest')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainApp.session')),
                ('text_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ChainApp.textstudy')),
            ],
            options={
                'verbose_name': 'Text Study Reservation',
                'verbose_name_plural': 'Text Study Reservations',
            },
        ),
        migrations.DeleteModel(
            name='Gemarot',
        ),
        migrations.DeleteModel(
            name='Gemara',
        ),
        migrations.DeleteModel(
            name='Seder',
        ),
        migrations.DeleteModel(
            name='Massekhet',
        ),
        migrations.DeleteModel(
            name='Michna',
        ),
    ]
