# Generated by Django 5.0.3 on 2024-09-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChainApp', '0005_textstudy_remove_gemara_choose_gemarot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textstudy',
            name='livre',
            field=models.CharField(default='', max_length=255),
        ),
    ]
