deployment:
  tasks:
    - command: source /home/hpjh3807/virtualenv/web/staging-PetiteJerusalem/3.11/bin/activate && cd /home/hpjh3807/web/staging-PetiteJerusalem
    - command: pip install -r requirements.txt
    - command: python manage.py migrate
    - command: python manage.py collectstatic --noinput
